apiVersion: batch/v1
kind: Job
metadata:
  name: migration
spec:
  template:
    spec:
      containers:
      - name: migration
        image: migrationservice:dev        
      restartPolicy: Never
  backoffLimit: 4